plotVar:
  label : 'Two variables comparison'
  parameters:
    startDate:
      label : 'start Date'
      type: date
      format: yyyy-mm-dd
      dateValue: Y-m-d
    endDate:
      label : 'end Date'
      type: date
      format: yyyy-mm-dd
      dateValue: Y-m-d
    nameVar:
      label : 'Variables'
      type: list
      RfunctionValues : listVariables
      required : true
    smoothing:
      label : 'smoothing'
      type: boolean
      defaultValue: false
    token:
      type: string
      visibility: hidden
      required : true
    wsUrl:
      type: string
      visibility: hidden
      required : true
