plotVar:
  label : 'Variable comparison'
  parameters:
    startDate:
      label : 'start Date'
      type: date
      format: yyyy-dd-mm
      dateValue: Y-m-d
    endDate:
      label : 'end Date'
      type: date
      format: yyyy-dd-mm
      dateValue: Y-m-d
    nameVar:
      label : 'Variables'
      valueType: list
      RfunctionValues : listVariables
    smoothing:
      label : 'smoothing'
      type: boolean
      default: false
    token:
      type: string
      visibility: hidden
    wsUrl:
      type: string
      visibility: hidden
