# function available minimum required
availableFunctions:
  - plotDemo
  - plotVar
  - plotVarRel
# web client integrated function configuration
plotVar:
  label : 'Compare two variables'
  type : graphic
  graphicType : plotly
  linkedFunctions :
    getDF:
      label : 'See compute data'
      name : getDF
      type : grid
      parameters :
        - startDate
        - endDate
        - varURI
        - smoothing
        - token
        - wsUrl
  formParameters:  # form parameters 
    startDate:
      label : 'Start date of data'
      type: date
      format: yyyy-mm-dd
      dateValue: Y-m-d
    endDate:
      label : 'End date of data'
      type: date
      format: yyyy-mm-dd
      dateValue: Y-m-d
    varURI:
      label : 'Variables'
      type: list
      maxSelectedItem : 2
      RfunctionValues : listVariables
      required : true
    smoothing:
      label : 'Smoothing'
      type: boolean
      defaultValue: false
    token:
      type: string
      visibility: hidden
      required : true
    wsUrl:
      type: string
      visibility: hidden
      required : true
plotDemo:
  label : 'Compare two variables'
  type : graphic
  graphicType : plotly
  linkedFunctions :
    getDF:
      label : 'See compute data'
      name : getDF
      type : grid
      parameters :
        - startDate
        - endDate
        - varURI
        - smoothing
        - token
        - wsUrl
  formParameters:
    startDate:
      label : 'Start date of data'
      type: date
      format: yyyy-mm-dd
      dateValue: Y-m-d
    endDate:
      label : 'End date of data'
      type: date
      format: yyyy-mm-dd
      dateValue: Y-m-d
    varURI:
      label : 'Variables'
      type: list
      maxSelectedItem : 2
      RfunctionValues : listVariables
      required : true
    smoothing:
      label : 'Smoothing'
      type: boolean
      defaultValue: false
    token:
      type: string
      visibility: hidden
      required : true
    wsUrl:
      type: string
      visibility: hidden
      required : true
plotVarRel:
  label : 'Confront two variables'
  type : graphic
  graphicType : plotly
  formParameters:
    startDate:
      label : 'Start date of data'
      type: date
      format: yyyy-mm-dd
      dateValue: Y-m-d
    endDate:
      label : 'End date of data'
      type: date
      format: yyyy-mm-dd
      dateValue: Y-m-d
    varY:
      label : 'Variable Y'
      type: list
      RfunctionValues : listVariables
      maxSelectedItem : 1
      required : true
    varX:
      label : 'Variable X'
      type: list
      RfunctionValues : listVariables
      maxSelectedItem : 1
      required : true
    trend:
      label : 'Trend'
      type: boolean
      defaultValue: false
    token:
      type: string
      visibility: hidden
      required : true
    wsUrl:
      type: string
      visibility: hidden
      required : true
